name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10', '12']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
