# This workflow will run tests using node

name: Test Node.js Package

on:
  push:
  pull_request:
    branches:
      - master
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
